import 'package:flutter/material.dart';
import 'package:flutter_application_1/models/item.dart';

final List<Item> items = [
  Item(
    id: 0,
    tipo: 'categoria',
    nombre: 'Panaderías',
    descripcion: 'Los mejores restaurantes de la ciudad',
    icono: Icons.bakery_dining,
    color: Colors.amber,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
    reviews: [
      Item(
        id: 3,
        tipo: 'item',
        nombre: 'Zuri',
        descripcion: 'En 10 y 64',
        rateTipo: 'stars',
        rateIcon: Icons.star_rounded,
        rateValue: 4,
      ),
      Item(
        id: 4,
        tipo: 'item',
        nombre: 'La Capital',
        descripcion: 'En 9 y 65',
        rateTipo: 'stars',
        rateIcon: Icons.star_rounded,
        rateValue: 3,
      ),
    ],
  ),
  Item(
    id: 2,
    tipo: 'categoria',
    nombre: 'Películas',
    descripcion: 'Las mejores películas del año',
    icono: Icons.movie,
    rateTipo: 'thumbs',
    rateIcon: Icons.thumb_up,
    reviews: [
      Item(
        id: 5,
        tipo: 'item',
        nombre: 'Blade Runner 2049',
        descripcion: 'Película de ciencia ficción, secuela de Blade Runner',
        rateTipo: 'thumbs',
        rateIcon: Icons.thumb_up,
        rateValue: 1,
      ),
      Item(
        id: 9,
        tipo: 'item',
        nombre: 'Papá se volvió loco',
        descripcion: 'Prometía más, medio pelo',
        rateTipo: 'thumbs',
        rateIcon: Icons.thumb_up,
        rateValue: 0,
      ),
    ],
  ),
  Item(
    id: 6,
    tipo: 'categoria',
    nombre: 'Cafés',
    descripcion: 'Las mejores cafeterías de la city',
    icono: Icons.coffee,
    color: Colors.red,
    rateTipo: 'number',
    rateIcon: null,
    reviews: [
      Item(
        id: 7,
        tipo: 'item',
        nombre: 'Mumi\'s',
        descripcion: 'Caro pero bueno, 50 e/10 y 11',
        rateTipo: 'number',
        rateIcon: null,
        rateValue: 8.5,
      ),
      Item(
        id: 8,
        tipo: 'item',
        nombre: 'Starbucks',
        descripcion:
            'Caro, café solo malo, frapuccinos et al, en Baxar y 11 y 49',
        rateTipo: 'number',
        rateIcon: null,
        rateValue: 7,
      ),
    ],
  ),
  Item(
    id: 0,
    tipo: 'categoria',
    nombre: 'Ropa',
    descripcion: 'Los mejores locales de ropa de la ciudad',
    icono: Icons.emoji_people_rounded,
    color: Colors.blue,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
    reviews: [],
  ),
  Item(
    id: 0,
    tipo: 'categoria',
    nombre: 'Casas de té',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.emoji_food_beverage_rounded,
    color: Colors.green,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
    reviews: [],
  ),
  Item(
    id: 0,
    tipo: 'categoria',
    nombre: 'Rock',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.headphones_rounded,
    color: Colors.black,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
    reviews: [],
  ),
  Item(
    id: 0,
    tipo: 'categoria',
    nombre: 'Pintores',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.brush_rounded,
    color: Colors.deepPurple,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
    reviews: [],
  ),
  Item(
    id: 0,
    tipo: 'categoria',
    nombre: 'Pizzerías',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.local_pizza_rounded,
    color: Colors.amber,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
    reviews: [],
  ),
  Item(
    id: 0,
    tipo: 'categoria',
    nombre: 'Trekking!',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.landscape_rounded,
    color: Colors.teal,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
    reviews: [],
  ),
  Item(
    id: 0,
    tipo: 'categoria',
    nombre: 'Baressss',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.liquor_rounded,
    color: Colors.deepOrange,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
    reviews: [],
  ),
  Item(
    id: 0,
    tipo: 'categoria',
    nombre: 'Destinos',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.airplanemode_active_rounded,
    color: Colors.pink[400],
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
    reviews: [],
  ),
];
