import 'package:flutter/material.dart';
import 'package:flutter_application_1/models/item.dart';
import 'package:flutter_application_1/models/category.dart';

final List<dynamic> items = [
  Category(
    uid: '0',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Panaderías',
    descripcion: 'Los mejores restaurantes de la ciudad',
    icono: Icons.bakery_dining,
    color: Colors.amber,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
  ),
  Item(
    uid: '3',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Zuri',
    descripcion: 'En 10 y 64',
    rateValue: 4,
    categoryId: '0',
  ),
  Item(
    uid: '4',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'La Capital',
    descripcion: 'En 9 y 65',
    rateValue: 3,
    categoryId: '0',
  ),
  Category(
    uid: '2',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Películas',
    descripcion: 'Las mejores películas del año',
    color: Colors.deepPurple,
    icono: Icons.movie,
    rateTipo: 'thumbs',
    rateIcon: Icons.thumb_up,
  ),
  Item(
    uid: '5',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Blade Runner 2049',
    descripcion: 'Película de ciencia ficción, secuela de Blade Runner',
    rateValue: 1,
    categoryId: '2',
  ),
  Item(
    uid: '9',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Papá se volvió loco',
    descripcion: 'Prometía más, medio pelo',
    rateValue: 0,
    categoryId: '2',
  ),
  Category(
    uid: '6',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Cafés',
    descripcion: 'Las mejores cafeterías de la city',
    icono: Icons.coffee,
    color: Colors.red,
    rateTipo: 'number',
    rateIcon: null,
  ),
  Item(
    uid: '7',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Mumi\'s',
    descripcion: 'Caro pero bueno, 50 e/10 y 11',
    rateValue: 8.5,
    categoryId: '6',
  ),
  Item(
    uid: '8',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Starbucks',
    descripcion: 'Caro, café solo malo, frapuccinos et al, en Baxar y 11 y 49',
    rateValue: 7,
    categoryId: '6',
  ),
  Category(
    uid: '0',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Ropa',
    descripcion: 'Los mejores locales de ropa de la ciudad',
    icono: Icons.emoji_people_rounded,
    color: Colors.blue,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
  ),
  Category(
    uid: '0',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Casas de té',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.emoji_food_beverage_rounded,
    color: Colors.green,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
  ),
  Category(
    uid: '0',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Rock',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.headphones_rounded,
    color: Colors.black,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
  ),
  Category(
    uid: '0',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Pintores',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.brush_rounded,
    color: Colors.deepPurple,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
  ),
  Category(
    uid: '0',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Pizzerías',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.local_pizza_rounded,
    color: Colors.amber,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
  ),
  Category(
    uid: '0',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Trekking!',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.landscape_rounded,
    color: Colors.teal,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
  ),
  Category(
    uid: '0',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Baressss',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.liquor_rounded,
    color: Colors.deepOrange,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
  ),
  Category(
    uid: '0',
    userId: 'zMuMpz9Gd0d6gD6sPjTChMPo65y2',
    nombre: 'Destinos',
    descripcion: 'Las mejores casas de té de la ciudad',
    icono: Icons.airplanemode_active_rounded,
    color: Colors.pink,
    rateTipo: 'stars',
    rateIcon: Icons.star_rounded,
  ),
];
