// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcXVLT0SJ_uveP957Deq20sec2UOW_9Oo',
    appId: '1:238233869082:web:db9e9546e96c4b50baeaa3',
    messagingSenderId: '238233869082',
    projectId: 'rate-all',
    authDomain: 'rate-all.firebaseapp.com',
    storageBucket: 'rate-all.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkM8o6tQt8MNzl6Bnbed7VfZFZ0d4DydM',
    appId: '1:238233869082:android:105dc981c0d95c8bbaeaa3',
    messagingSenderId: '238233869082',
    projectId: 'rate-all',
    storageBucket: 'rate-all.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2NH9K5OKX1u1TVK6k46QHUfXgurWiHAY',
    appId: '1:238233869082:ios:4512725c681964cebaeaa3',
    messagingSenderId: '238233869082',
    projectId: 'rate-all',
    storageBucket: 'rate-all.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2NH9K5OKX1u1TVK6k46QHUfXgurWiHAY',
    appId: '1:238233869082:ios:4512725c681964cebaeaa3',
    messagingSenderId: '238233869082',
    projectId: 'rate-all',
    storageBucket: 'rate-all.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcXVLT0SJ_uveP957Deq20sec2UOW_9Oo',
    appId: '1:238233869082:web:60d7b8415f5fedfbbaeaa3',
    messagingSenderId: '238233869082',
    projectId: 'rate-all',
    authDomain: 'rate-all.firebaseapp.com',
    storageBucket: 'rate-all.firebasestorage.app',
  );
}
